export const ADD_EXPENSE = "ADD_EXPENSE";
export const ADD_USERS = "ADD_USERS";
export const REMOVE_USERS = "REMOVE_USERS";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY= "REMOVE_CATEGORY";
export const DELETE_EXPENSE = "DELETE_EXPENSE"